using Lists.Classes;

ArrayList arrs = new ArrayList();
// arrs.PrintArr();
// arrs.AddToIndex(0,99);
// arrs.AddToIndex(1,50);
// arrs.AddToStart(10);
// arrs.Add(12);
// arrs.Add(14);
// arrs.MoveOnXOnRigth(3);
// arrs.MoveOnXOnLeft(3);
// arrs.AddToIndex(2,61);
// arrs.AddToIndex(3,70);
// arrs.AddToIndex(4,80);
// arrs.AddToIndex(5,40);
// arrs.AddToIndex(6,39);
// arrs.AddToIndex(7,59);
// arrs.AddToIndex(8,29);
// arrs.AddToIndex(9,19);
// arrs.RemoveFirstElement();
// arrs.RemoveLastElement();
// arrs.RemoveAtIndex(6);
// arrs.RemoveAtIndex(0);
// arrs.RemoveAtIndex(3);
// arrs.RemoveAtIndex(3);
// arrs.RemoveLastFewElements(1);
// arrs.RemoveFirstFewElements(1);
// int desired = arrs.GetFirstIndexFromValue(2);
// Console.WriteLine(desired);
// arrs.ArrayReverse();
// int max = arrs.FindMaxValueOfArray();
// Console.WriteLine(max);
// int min = arrs.FindMinValueOfArray();
// Console.WriteLine(min);
// int indexOfMaxValue = arrs.FindIndexofMaxValueOfArray();
// Console.WriteLine(indexOfMaxValue);
// int indexOfMinValue = arrs.FindIndexofMinValueOfArray();
// Console.WriteLine(indexOfMinValue);
// arrs.SortToMin();
// arrs.SortToMax();
// int indexOfDeleted = arrs.DeleteByValue(3);
// Console.WriteLine(indexOfDeleted);
// arrs.DeleteByValue(1);
// arrs.DeleteByValues(1);
// arrs.RemoveFewElementsByIndex(0,2);
// Console.Write(arrs.Length);
arrs.PrintArr();
// int q = arrs.ReturnLengthOfArray();
// Console.WriteLine(q);
// Console.WriteLine();
// arrs.PrintArr();
Console.Read();