using Lists.Classes;

ArrayList arrs = new ArrayList();
// arrs.PrintArr();
// arrs.AddToIndex(0,99);
// arrs.AddToIndex(1,50);
// arrs.AddToStart(10);
arrs.Add(12);
arrs.AddToIndex(2,60);
// arrs.AddToIndex(3,70);
// arrs.AddToIndex(4,80);
// arrs.AddToIndex(5,40);
// arrs.AddToIndex(6,39);
// arrs.AddToIndex(7,59);
// arrs.AddToIndex(8,29);
// arrs.AddToIndex(9,19);
// arrs.RemoveFirstElement();
// arrs.RemoveLastElement();
// arrs.RemoveAtIndex(6);
// arrs.RemoveAtIndex(3);
// arrs.RemoveLastFewElements(1);
// arrs.RemoveFirstFewElements(3);
// arrs.RemoveFewElementsByIndex(2,2);
// Console.Write(arrs.Length);
arrs.PrintArr();
int q = arrs.ReturnLengthOfArray();
Console.WriteLine(q);
Console.WriteLine();
// arrs.PrintArr();
Console.Read();